//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGasolinera.wsBombaCombustible {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsBombaCombustible.wsBombacombustibleSoap")]
    public interface wsBombacombustibleSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_bombacombustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_bombacombustible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_bombacombustible", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_bombacombustibleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_bombacombustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_bombacombustible(double capacidad, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_bombacombustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_bombacombustibleAsync(double capacidad, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_bombacombustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_bombacombustible(int idBombaCombustible, double capacidad, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_bombacombustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_bombacombustibleAsync(int idBombaCombustible, double capacidad, int idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_bombacombustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_bombacombustible(int idBombaCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_bombacombustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_bombacombustibleAsync(int idBombaCombustible);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsBombacombustibleSoapChannel : proyectoGasolinera.wsBombaCombustible.wsBombacombustibleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsBombacombustibleSoapClient : System.ServiceModel.ClientBase<proyectoGasolinera.wsBombaCombustible.wsBombacombustibleSoap>, proyectoGasolinera.wsBombaCombustible.wsBombacombustibleSoap {
        
        public wsBombacombustibleSoapClient() {
        }
        
        public wsBombacombustibleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsBombacombustibleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBombacombustibleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBombacombustibleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listado_bombacombustible() {
            return base.Channel.listado_bombacombustible();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_bombacombustibleAsync() {
            return base.Channel.listado_bombacombustibleAsync();
        }
        
        public int insertar_bombacombustible(double capacidad, int idSucursal) {
            return base.Channel.insertar_bombacombustible(capacidad, idSucursal);
        }
        
        public System.Threading.Tasks.Task<int> insertar_bombacombustibleAsync(double capacidad, int idSucursal) {
            return base.Channel.insertar_bombacombustibleAsync(capacidad, idSucursal);
        }
        
        public int actualizar_bombacombustible(int idBombaCombustible, double capacidad, int idSucursal) {
            return base.Channel.actualizar_bombacombustible(idBombaCombustible, capacidad, idSucursal);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_bombacombustibleAsync(int idBombaCombustible, double capacidad, int idSucursal) {
            return base.Channel.actualizar_bombacombustibleAsync(idBombaCombustible, capacidad, idSucursal);
        }
        
        public int eliminar_bombacombustible(int idBombaCombustible) {
            return base.Channel.eliminar_bombacombustible(idBombaCombustible);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_bombacombustibleAsync(int idBombaCombustible) {
            return base.Channel.eliminar_bombacombustibleAsync(idBombaCombustible);
        }
    }
}
