//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGasolinera.WServicioWeb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WServicioWeb.wsUsuarioSoap")]
    public interface wsUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_usuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_usuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet usuario([System.ServiceModel.MessageParameterAttribute(Name="usuario")] string usuario1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> usuarioAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_usuario(int idEmpleado, int idTipoUsuario, string nombreUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_usuarioAsync(int idEmpleado, int idTipoUsuario, string nombreUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_usuario(int idUsuario, int idEmpleado, int idTipoUsuario, string nombreUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_usuarioAsync(int idUsuario, int idEmpleado, int idTipoUsuario, string nombreUsuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_usuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_usuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsUsuarioSoapChannel : proyectoGasolinera.WServicioWeb.wsUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsUsuarioSoapClient : System.ServiceModel.ClientBase<proyectoGasolinera.WServicioWeb.wsUsuarioSoap>, proyectoGasolinera.WServicioWeb.wsUsuarioSoap {
        
        public wsUsuarioSoapClient() {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listado_usuarios() {
            return base.Channel.listado_usuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_usuariosAsync() {
            return base.Channel.listado_usuariosAsync();
        }
        
        public System.Data.DataSet usuario(string usuario1, string password) {
            return base.Channel.usuario(usuario1, password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> usuarioAsync(string usuario, string password) {
            return base.Channel.usuarioAsync(usuario, password);
        }
        
        public int insertar_usuario(int idEmpleado, int idTipoUsuario, string nombreUsuario, string password) {
            return base.Channel.insertar_usuario(idEmpleado, idTipoUsuario, nombreUsuario, password);
        }
        
        public System.Threading.Tasks.Task<int> insertar_usuarioAsync(int idEmpleado, int idTipoUsuario, string nombreUsuario, string password) {
            return base.Channel.insertar_usuarioAsync(idEmpleado, idTipoUsuario, nombreUsuario, password);
        }
        
        public int actualizar_usuario(int idUsuario, int idEmpleado, int idTipoUsuario, string nombreUsuario, string password) {
            return base.Channel.actualizar_usuario(idUsuario, idEmpleado, idTipoUsuario, nombreUsuario, password);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_usuarioAsync(int idUsuario, int idEmpleado, int idTipoUsuario, string nombreUsuario, string password) {
            return base.Channel.actualizar_usuarioAsync(idUsuario, idEmpleado, idTipoUsuario, nombreUsuario, password);
        }
        
        public int eliminar_usuario(int idUsuario) {
            return base.Channel.eliminar_usuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_usuarioAsync(int idUsuario) {
            return base.Channel.eliminar_usuarioAsync(idUsuario);
        }
    }
}
