//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGasolinera.wsTipoUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsTipoUsuario.wsTipoUsuarioSoap")]
    public interface wsTipoUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_tipousuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_tipousuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_tipousuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_tipousuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_tipousuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_tipousuario(string nombreTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_tipousuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_tipousuarioAsync(string nombreTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tipousuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_tipousuario(int idTipoUsuario, string nombreTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_tipousuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_tipousuarioAsync(int idTipoUsuario, string nombreTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_tipousuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_tipousuario(int idTipoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_tipousuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_tipousuarioAsync(int idTipoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTipoUsuarioSoapChannel : proyectoGasolinera.wsTipoUsuario.wsTipoUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTipoUsuarioSoapClient : System.ServiceModel.ClientBase<proyectoGasolinera.wsTipoUsuario.wsTipoUsuarioSoap>, proyectoGasolinera.wsTipoUsuario.wsTipoUsuarioSoap {
        
        public wsTipoUsuarioSoapClient() {
        }
        
        public wsTipoUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTipoUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listado_tipousuario() {
            return base.Channel.listado_tipousuario();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_tipousuarioAsync() {
            return base.Channel.listado_tipousuarioAsync();
        }
        
        public int insertar_tipousuario(string nombreTipoUsuario) {
            return base.Channel.insertar_tipousuario(nombreTipoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> insertar_tipousuarioAsync(string nombreTipoUsuario) {
            return base.Channel.insertar_tipousuarioAsync(nombreTipoUsuario);
        }
        
        public int actualizar_tipousuario(int idTipoUsuario, string nombreTipoUsuario) {
            return base.Channel.actualizar_tipousuario(idTipoUsuario, nombreTipoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_tipousuarioAsync(int idTipoUsuario, string nombreTipoUsuario) {
            return base.Channel.actualizar_tipousuarioAsync(idTipoUsuario, nombreTipoUsuario);
        }
        
        public int eliminar_tipousuario(int idTipoUsuario) {
            return base.Channel.eliminar_tipousuario(idTipoUsuario);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_tipousuarioAsync(int idTipoUsuario) {
            return base.Channel.eliminar_tipousuarioAsync(idTipoUsuario);
        }
    }
}
