//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGasolinera.wsTipoCombustible {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsTipoCombustible.wsTipoCombustibleSoap")]
    public interface wsTipoCombustibleSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado_Tipo_De_Combustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listado_Tipo_De_Combustible();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listado_Tipo_De_Combustible", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Listado_Tipo_De_CombustibleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_Tipo_De_Combustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insertar_Tipo_De_Combustible(string nombreTipoCombustible, double PrecioCombustibleAutoservicio, double PrecioCombustibleServicioCompleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insertar_Tipo_De_Combustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> Insertar_Tipo_De_CombustibleAsync(string nombreTipoCombustible, double PrecioCombustibleAutoservicio, double PrecioCombustibleServicioCompleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_Combustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_Combustible(int idTipoCombustible, string nombreTipoCombustible, double PrecioAutoservicio, double PrecioServicioCOmpleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_Combustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_CombustibleAsync(int idTipoCombustible, string nombreTipoCombustible, double PrecioAutoservicio, double PrecioServicioCOmpleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_Combustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_Combustible(int idTipoCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_Combustible", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_CombustibleAsync(int idTipoCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_Combustible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet buscar_Combustible(int idCombustible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar_Combustible", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> buscar_CombustibleAsync(int idCombustible);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsTipoCombustibleSoapChannel : proyectoGasolinera.wsTipoCombustible.wsTipoCombustibleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsTipoCombustibleSoapClient : System.ServiceModel.ClientBase<proyectoGasolinera.wsTipoCombustible.wsTipoCombustibleSoap>, proyectoGasolinera.wsTipoCombustible.wsTipoCombustibleSoap {
        
        public wsTipoCombustibleSoapClient() {
        }
        
        public wsTipoCombustibleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsTipoCombustibleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoCombustibleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsTipoCombustibleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listado_Tipo_De_Combustible() {
            return base.Channel.Listado_Tipo_De_Combustible();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Listado_Tipo_De_CombustibleAsync() {
            return base.Channel.Listado_Tipo_De_CombustibleAsync();
        }
        
        public int Insertar_Tipo_De_Combustible(string nombreTipoCombustible, double PrecioCombustibleAutoservicio, double PrecioCombustibleServicioCompleto) {
            return base.Channel.Insertar_Tipo_De_Combustible(nombreTipoCombustible, PrecioCombustibleAutoservicio, PrecioCombustibleServicioCompleto);
        }
        
        public System.Threading.Tasks.Task<int> Insertar_Tipo_De_CombustibleAsync(string nombreTipoCombustible, double PrecioCombustibleAutoservicio, double PrecioCombustibleServicioCompleto) {
            return base.Channel.Insertar_Tipo_De_CombustibleAsync(nombreTipoCombustible, PrecioCombustibleAutoservicio, PrecioCombustibleServicioCompleto);
        }
        
        public int actualizar_Combustible(int idTipoCombustible, string nombreTipoCombustible, double PrecioAutoservicio, double PrecioServicioCOmpleto) {
            return base.Channel.actualizar_Combustible(idTipoCombustible, nombreTipoCombustible, PrecioAutoservicio, PrecioServicioCOmpleto);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_CombustibleAsync(int idTipoCombustible, string nombreTipoCombustible, double PrecioAutoservicio, double PrecioServicioCOmpleto) {
            return base.Channel.actualizar_CombustibleAsync(idTipoCombustible, nombreTipoCombustible, PrecioAutoservicio, PrecioServicioCOmpleto);
        }
        
        public int eliminar_Combustible(int idTipoCombustible) {
            return base.Channel.eliminar_Combustible(idTipoCombustible);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_CombustibleAsync(int idTipoCombustible) {
            return base.Channel.eliminar_CombustibleAsync(idTipoCombustible);
        }
        
        public System.Data.DataSet buscar_Combustible(int idCombustible) {
            return base.Channel.buscar_Combustible(idCombustible);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> buscar_CombustibleAsync(int idCombustible) {
            return base.Channel.buscar_CombustibleAsync(idCombustible);
        }
    }
}
