//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGasolinera.wsEmpleado {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEmpleado.wsEmpleadoSoap")]
    public interface wsEmpleadoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_empleados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet listado_empleados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listado_empleados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> listado_empleadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertar_empleado(int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar_empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertar_empleadoAsync(int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int actualizar_empleado(int idEmpleado, int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar_empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> actualizar_empleadoAsync(int idEmpleado, int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int eliminar_empleado(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<int> eliminar_empleadoAsync(int idEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEmpleadoSoapChannel : proyectoGasolinera.wsEmpleado.wsEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEmpleadoSoapClient : System.ServiceModel.ClientBase<proyectoGasolinera.wsEmpleado.wsEmpleadoSoap>, proyectoGasolinera.wsEmpleado.wsEmpleadoSoap {
        
        public wsEmpleadoSoapClient() {
        }
        
        public wsEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet listado_empleados() {
            return base.Channel.listado_empleados();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> listado_empleadosAsync() {
            return base.Channel.listado_empleadosAsync();
        }
        
        public int insertar_empleado(int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado) {
            return base.Channel.insertar_empleado(idSucursal, idPuesto, nombreEmpleado, telefono, emailEmpleado);
        }
        
        public System.Threading.Tasks.Task<int> insertar_empleadoAsync(int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado) {
            return base.Channel.insertar_empleadoAsync(idSucursal, idPuesto, nombreEmpleado, telefono, emailEmpleado);
        }
        
        public int actualizar_empleado(int idEmpleado, int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado) {
            return base.Channel.actualizar_empleado(idEmpleado, idSucursal, idPuesto, nombreEmpleado, telefono, emailEmpleado);
        }
        
        public System.Threading.Tasks.Task<int> actualizar_empleadoAsync(int idEmpleado, int idSucursal, int idPuesto, string nombreEmpleado, int telefono, string emailEmpleado) {
            return base.Channel.actualizar_empleadoAsync(idEmpleado, idSucursal, idPuesto, nombreEmpleado, telefono, emailEmpleado);
        }
        
        public int eliminar_empleado(int idEmpleado) {
            return base.Channel.eliminar_empleado(idEmpleado);
        }
        
        public System.Threading.Tasks.Task<int> eliminar_empleadoAsync(int idEmpleado) {
            return base.Channel.eliminar_empleadoAsync(idEmpleado);
        }
    }
}
